{
 "title": "Service Level Objective",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(slo:window,namespace)"
    }
   },
   {
    "name": "name",
    "label": "Name",
    "query": {
     "query": "label_values(slo:window{namespace=\"$namespace\"},name)"
    }
   },
   {
    "name": "slo",
    "label": "SLO",
    "query": {
     "query": "label_values(slo:window{namespace=\"$namespace\", name=\"$name\"},slo)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Objective",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "slo:objective{namespace=\"$namespace\", name=\"$name\", slo=\"$slo\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Window",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "slo:window{namespace=\"$namespace\", name=\"$name\", slo=\"$slo\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "slo:availability{namespace=\"$namespace\", name=\"$name\", slo=\"$slo\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "((slo:availability{namespace=\"$namespace\", name=\"$name\", slo=\"$slo\"} - slo:objective{namespace=\"$namespace\", name=\"$name\", slo=\"$slo\"})) / (1 - slo:objective{namespace=\"$namespace\", name=\"$name\", slo=\"$slo\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current BurnRate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "slo:burnrate{window=\"5m\", namespace=\"$namespace\", name=\"$name\", slo=\"$slo\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "((slo:availability{namespace=\"$namespace\", name=\"$name\", slo=\"$slo\"} - slo:objective{namespace=\"$namespace\", name=\"$name\", slo=\"$slo\"})) / (1 - slo:objective{namespace=\"$namespace\", name=\"$name\", slo=\"$slo\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BurnRate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "slo:burnrate{window=\"5m\", namespace=\"$namespace\", name=\"$name\", slo=\"$slo\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "slo:total{namespace=\"$namespace\", name=\"$name\", slo=\"$slo\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "slo:errors_total{namespace=\"$namespace\", name=\"$name\", slo=\"$slo\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}