apiVersion: v1
kind: Service
metadata:
  name: {{ include "slo-operator.fullname" . }}
  labels:
    {{- include "slo-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: http
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: metrics
  selector:
    {{- include "slo-operator.selectorLabels" . | nindent 4 }}
